services: docker

before_install:
  - docker -v
install:
  # Start the docker stuff
  - cd travis
  - docker-compose up -d
  - sleep 10
script:
  - docker-compose exec headnode bash -c "hostname headnode.cluster"
  - docker-compose exec computenode bash -c "hostname computenode.cluster"
  - docker-compose exec headnode bash -c "echo headnode.cluster > /etc/hostname"
  - docker-compose exec computenode bash -c "echo computenode.cluster > /etc/hostname"
  - docker-compose exec headnode bash -c "cd /ansible && ansible-playbook -i inventory site.yml --syntax-check"
  - docker-compose exec headnode bash -c "cd /ansible && ansible-playbook -i inventory site.yml"
  - sleep 10
  - docker-compose exec headnode bash -c  "hostname -s; hostname"
  - docker-compose exec computenode bash -c  "hostname -s; hostname"
  - docker-compose exec headnode bash -c "cat /tools/admin/slurm/etc/slurm.conf"
  - docker-compose exec headnode bash -c "ls /tools/admin/slurm"
  - docker-compose exec headnode bash -c "ps aux | grep slurm"
  - docker-compose exec computenode bash -c "ps aux | grep slurm"
  - docker-compose exec headnode bash -c "journalctl --unit=slurmctld -n 100 --no-pager --full"
  - docker-compose exec computenode bash -c "journalctl --unit=slurmd -n 100 --no-pager --full"
  - docker-compose exec headnode bash -c "/tools/admin/slurm/bin/sinfo"
