services: docker

before_install:
  - docker -v
install:
  # Start the docker stuff
  - cd travis
  - docker-compose up -d
  - sleep 10
script:
  - docker-compose exec headnode bash -c "cd /ansible && ansible-playbook -i inventory site.yml --syntax-check"
  - docker-compose exec headnode bash -c "cd /ansible && ansible-playbook -i inventory site.yml"
  - sleep 10
  - docker-compose exec headnode bash -c "ls /tools/admin/slurm"
  - docker-compose exec headnode bash -c "ps aux | grep slurm"
  - docker-compose exec computenode bash -c "ps aux | grep slurm"
  - docker-compose exec headnode bash -c "systemctl status slurmctld --no-pager --full"
  - docker-compose exec computenode bash -c "systemctl status slurmd --no-pager --full"
  - docker-compose exec headnode bash -c "/tools/admin/slurm/bin/sinfo"
