---

- name: Install dependencies for Slurm runtime
  apt:
    name: [munge, libmunge-dev, libmunge2, procps, bsd-mailx]
    state: present

- name: Ensure key-based authentication
  block:
    - name: Check if pub key exists on slurm master
      stat:
        path: /root/.ssh/id_rsa
      register: stat_ssh
      when:
        - headnode is defined

    - name: Generate SSH keys on slurm master
      shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
      args:
        creates: /root/.ssh/id_rsa
      when:
        - headnode is defined
        - ("stat" in stat_ssh) and (stat_ssh.stat.exists == False | default(False))

    - name: Retrieve public key from slurm master
      slurp:
        src:  /root/.ssh/id_rsa.pub
      register: pubkey
      when: 
        - headnode is defined

    - name: Distribute public key to cluster
      lineinfile:
        path: /root/.ssh/authorized_keys
        state: present
        line: "{{ hostvars[groups['slurm'][0]]['pubkey']['content'] | b64decode }}"

- name: Ensure munge
  block:
    - name: Copy munge.service
      copy:
          src: "{{ role_path }}/files/munge.service"
          dest: /lib/systemd/system/munge.service
          owner: root
          group: root
          mode: 0644
      notify:
        - systemd restart munge

    - name: Retrieve key for munge cluster
      fetch:
        src: /etc/munge/munge.key
        dest: "{{ conf_dir }}/munge.key"
        flat: yes
      when:
        - not munge_external_key
        - "slurm_builder is defined"

    - name: Create munge directory
      file:
        path: /etc/munge
        state: directory

    - name: Distribute munge key to all machines
      copy:
        src: "{{ conf_dir }}/munge.key"
        dest: /etc/munge/munge.key
        force: yes
        mode: 0400
      when:
        - not munge_external_key
      notify:
        - systemd start munge

    - name: Distribute munge key to all machines
      copy:
        content: "{{ munge_external_key_data }}"
        dest: /etc/munge/munge.key
        force: yes
        mode: 0400
      when:
        - munge_external_key
      notify:
        - systemd restart munge

- name: Ensure slurm group
  group:
    name: slurm
    state: present

- name: Ensure slurm user
  user:
    name: slurm
    state: present
    group: slurm

- name: Create runtime directories
  file:
    path: "{{ item }}"
    owner: slurm
    group: slurm
    state: directory
  loop:
    - /var/run/slurm
    - /var/spool/slurm
    - /var/log/slurm