---

- name: Set fact about hosts for templates
  set_fact:
    hpc: "{{ groups['slurm'] }}"
  when: headnode is defined
  run_once: True
  
- name: Template out the Slurm conf files
  template:
    src: "{{ role_path }}/files/{{ item }}.j2"
    dest: "{{ slurm_install_dir }}/etc/{{ item }}"
    owner: slurm
    group: slurm
    mode: 0644
  with_items:
    - cgroup.conf
    - cgroup_allowed_devices_file.conf
    - slurm.conf
    - slurmdbd.conf
  when: headnode is defined

- name: Template out the service files to the slurm controller
  template:
    src: "{{ role_path }}/files/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - slurmctld.service
    - slurmdbd.service
  when: headnode is defined

- name: Template out service files to all machines
  template:
    src: "{{ role_path }}/files/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - slurmd.service
  when: headnode is not defined