---

- name: Check if Database exists on machine
  wait_for: "host={{ db_host }} port={{ db_port }} timeout=1"
  register: varrr
  ignore_errors: yes

- name: Prepare database for Slurm
  include_tasks: 01_database.yml
  connection: local
  become: no
  when: "not varrr['failed']"

- name: Check if slurm is compiled/installed
  stat:
    path: "{{ slurm_install_dir }}"
  register: stat_result
  become: no
  
- name: Compile slurm 
  include_tasks: _compile.yml
  when: (stat_result.stat.exists == False) and (slurm_builder is defined)

- name: Install Slurm dependencies
  include_tasks: 02_dependencies.yml