- name: systemd start munge
  systemd:
    name: munge
    state: started
    daemon_reload: yes

- name: systemd stop munge
  systemd:
    name: munge
    state: stopped
    daemon_reload: yes
  ignore_errors: True

- name: systemd restart munge
  systemd:
    name: munge
    state: restarted
    daemon_reload: yes

- name: systemd restart slurmctld
  systemd:
    name: "slurmctld.service"
    state: restarted
    enabled: yes
    daemon_reload: yes
  when:
    - headnode is defined
    
- name: systemd restart slurmdbd
  systemd:
    name: "slurmdbd.service"
    state: restarted
    enabled: yes
    daemon_reload: yes
  when:
    - headnode is defined
    - slurm_use_db

- name: systemd restart slurmd
  systemd:
    name: slurmd.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  when:
    - headnode is not defined